### ISSUE TITLE
트리 구조로 만들기

### ISSUE THREAD

**Issue by seokunee** [seokunee/minishell#4]
- 토큰화 된 연결리스트 트리 구조로 만들기

**Comment by 42kko** [comment]
11/18

수정사항
- token 구조체에 추가된부분 : left, right (리스트에서 바로 트리구조로 바꾸려고 token안에 추가했습니다.)
- token 구조체의 변경사항 : prev를 추가해 양방향리스트로 변경했습니다.

누락파일 추가
'set_type_remove_operator ' 함수안에 사용되는 line_modity 부분이 누락되어 추가했습니다.
